import type { Play } from "./types";

const QB = { x: 50, y: 12 };

// Standard receiver start positions (y = 4 just above LOS, on LOS)
const POS = {
  farLeft: { x: 12, y: 4 },
  left: { x: 28, y: 4 },
  slotLeft: { x: 38, y: 4 },
  center: { x: 50, y: 4 },
  slotRight: { x: 62, y: 4 },
  right: { x: 72, y: 4 },
  farRight: { x: 88, y: 4 },
  backfield: { x: 38, y: 14 },
  backfieldRight: { x: 62, y: 14 },
};

export const PRESET_PLAYS: Play[] = [
  // ===== ZONE PASS =====
  {
    id: "spread-go",
    name: "Spread Go",
    defense: "zone",
    qb: QB,
    formation: "Trips Spread",
    purpose: "Stretch the deep zone with three verticals.",
    keyRead: "Read the safety; throw to the receiver he doesn't cover.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.left, route: "post", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "post", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "bunch-slants",
    name: "Bunch Slants",
    defense: "zone",
    qb: QB,
    formation: "Bunch Right",
    purpose: "Quick slants flood underneath zones.",
    keyRead: "Hit the first open slant window.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.left, route: "hitch", side: "left" },
      { id: "r2", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r3", x: 60, y: 4, route: "slant", side: "right" },
      { id: "r4", x: 68, y: 4, route: "slant", side: "right" },
      { id: "r5", x: 76, y: 4, route: "slant", side: "right" },
    ],
  },
  {
    id: "triangle-flood",
    name: "Triangle Flood",
    defense: "zone",
    qb: QB,
    formation: "Trips Right",
    purpose: "Three levels in one zone forces a choice.",
    keyRead: "High-low the flat defender.",
    tags: ["short", "third-long"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "dig", side: "left" },
      { id: "r2", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r4", ...POS.right, route: "out", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "four-verts",
    name: "Four Verticals",
    defense: "zone",
    qb: QB,
    formation: "Spread",
    purpose: "Four go routes stress every deep zone.",
    keyRead: "Find the seam between safeties.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "go", side: "left" },
      { id: "r3", ...POS.center, route: "go", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "curl-flat",
    name: "Curl-Flat",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose: "Classic high-low on the flat defender.",
    keyRead: "If flat defender drops, throw flat. If he sits, throw curl.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "curl", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "flat", side: "left" },
      { id: "r3", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "flat", side: "right" },
      { id: "r5", ...POS.farRight, route: "curl", side: "right" },
    ],
  },
  {
    id: "smash",
    name: "Smash",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose: "Hitch under, corner over: classic Cover-2 beater.",
    keyRead: "If corner sinks, hit hitch. If he stays flat, throw corner.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.left, route: "hitch", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "corner", side: "left" },
      { id: "r3", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r5", ...POS.right, route: "hitch", side: "right" },
    ],
  },
  {
    id: "screen-pass",
    name: "Bubble Screen",
    defense: "zone",
    qb: QB,
    formation: "Empty",
    purpose: "Quick lateral release with blockers.",
    keyRead: "Throw immediately to back; let blockers work.",
    tags: ["short", "screen"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.left, route: "block", side: "left" },
      { id: "r3", ...POS.center, route: "screen", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "block", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "stick",
    name: "Stick Concept",
    defense: "zone",
    qb: QB,
    formation: "Trips",
    purpose: "Three-level stretch on flat defender.",
    keyRead: "Read flat defender; stick or out.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "out", side: "right" },
      { id: "r4", ...POS.right, route: "curl", side: "right" },
      { id: "r5", ...POS.farRight, route: "flat", side: "right" },
    ],
  },
  {
    id: "levels",
    name: "Levels",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose: "Two in-routes at different depths attack zone seams.",
    keyRead: "Throw the deeper in-route if LB jumps shallow.",
    tags: ["short", "third-long"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "in", side: "left" },
      { id: "r2", ...POS.left, route: "dig", side: "left" },
      { id: "r3", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "hitch", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "snag",
    name: "Snag",
    defense: "zone",
    qb: QB,
    formation: "Trips Right",
    purpose: "Triangle stretch: corner over, snag under, flat wide.",
    keyRead: "High-low and inside-out the flat defender.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r4", ...POS.right, route: "curl", side: "right" },
      { id: "r5", ...POS.farRight, route: "flat", side: "right" },
    ],
  },
  {
    id: "y-stick",
    name: "Y Stick",
    defense: "zone",
    qb: QB,
    formation: "Trips Left",
    purpose: "Quick stick route vs. soft zone.",
    keyRead: "If flat defender widens, hit the stick.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "out", side: "left" },
      { id: "r2", ...POS.left, route: "curl", side: "left" },
      { id: "r3", ...POS.slotLeft, route: "flat", side: "left" },
      { id: "r4", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r5", ...POS.farRight, route: "post", side: "right" },
    ],
  },
  {
    id: "shallow-cross",
    name: "Shallow Cross",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose: "Shallow drag pulls underneath defenders.",
    keyRead: "Hit drag in stride away from coverage.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "drag", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "dig", side: "left" },
      { id: "r3", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "curl", side: "right" },
    ],
  },

  // ===== MAN PASS =====
  {
    id: "cross-routes",
    name: "Cross Routes",
    defense: "man",
    qb: QB,
    formation: "Doubles",
    purpose: "Crossing routes pick off man defenders.",
    keyRead: "Throw to the receiver who clears traffic first.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "cross", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "go", side: "left" },
      { id: "r3", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "cross", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "play-action-dig",
    name: "Play Action Dig",
    defense: "man",
    qb: QB,
    formation: "I-Form",
    purpose: "Fake handoff, hit the deep dig.",
    keyRead: "Sell fake, find dig in the void.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.left, route: "dig", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "post", side: "right" },
      { id: "r5", ...POS.farRight, route: "out", side: "right" },
    ],
  },
  {
    id: "mesh",
    name: "Mesh",
    defense: "man",
    qb: QB,
    formation: "Spread",
    purpose: "Two shallow crossers create a natural pick.",
    keyRead: "Throw to the receiver running away from coverage.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "cross", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "corner", side: "left" },
      { id: "r3", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r5", ...POS.farRight, route: "cross", side: "right" },
    ],
  },
  {
    id: "double-slants",
    name: "Double Slants",
    defense: "man",
    qb: QB,
    formation: "Doubles",
    purpose: "Quick-hitting slants beat tight man.",
    keyRead: "Throw to the leverage side.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.left, route: "slant", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "go", side: "left" },
      { id: "r3", ...POS.center, route: "slant", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "go", side: "right" },
      { id: "r5", ...POS.right, route: "slant", side: "right" },
    ],
  },
  {
    id: "wheel-post",
    name: "Wheel & Post",
    defense: "man",
    qb: QB,
    formation: "Trips Right",
    purpose: "Wheel route from back beats LB in man.",
    keyRead: "Look post first; check down to wheel.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "post", side: "left" },
      { id: "r2", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "in", side: "right" },
      { id: "r4", ...POS.right, route: "go", side: "right" },
      { id: "r5", ...POS.backfieldRight, route: "wheel", side: "right" },
    ],
  },
  {
    id: "drive",
    name: "Drive Concept",
    defense: "man",
    qb: QB,
    formation: "Doubles",
    purpose: "Shallow + dig combo crushes inside leverage.",
    keyRead: "Hit shallow vs. soft, dig vs. tight.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "dig", side: "left" },
      { id: "r2", ...POS.left, route: "drag", side: "left" },
      { id: "r3", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "corner", side: "right" },
    ],
  },
  {
    id: "iso-go",
    name: "Iso Go",
    defense: "man",
    qb: QB,
    formation: "Empty",
    purpose: "Isolate your best receiver one-on-one deep.",
    keyRead: "Throw to the matchup; everyone else clears.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "drag", side: "left" },
      { id: "r3", ...POS.center, route: "drag", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "drag", side: "right" },
      { id: "r5", ...POS.farRight, route: "out", side: "right" },
    ],
  },
  {
    id: "rub-slants",
    name: "Rub Slants",
    defense: "man",
    qb: QB,
    formation: "Bunch Right",
    purpose: "Bunch creates natural pick on slants.",
    keyRead: "Throw to receiver coming free from rub.",
    tags: ["short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r3", x: 60, y: 4, route: "slant", side: "right" },
      { id: "r4", x: 68, y: 4, route: "out", side: "right" },
      { id: "r5", x: 76, y: 4, route: "slant", side: "right" },
    ],
  },
  {
    id: "double-post",
    name: "Double Post",
    defense: "man",
    qb: QB,
    formation: "Doubles",
    purpose: "Two posts overload the deep middle.",
    keyRead: "Throw away from the deep safety.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "post", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "out", side: "left" },
      { id: "r3", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "in", side: "right" },
      { id: "r5", ...POS.farRight, route: "post", side: "right" },
    ],
  },
  {
    id: "switch-verts",
    name: "Switch Verticals",
    defense: "man",
    qb: QB,
    formation: "Spread",
    purpose: "Crossing releases pick man defenders deep.",
    keyRead: "Find the receiver who won the release.",
    tags: ["deep"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "corner", side: "left" },
      { id: "r3", ...POS.center, route: "go", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "stick-nod",
    name: "Stick-Nod",
    defense: "man",
    qb: QB,
    formation: "Trips Right",
    purpose: "Fake hitch then break upfield to beat tight man.",
    keyRead: "Sell the hitch, then look deep.",
    tags: ["deep", "trick"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "in", side: "left" },
      { id: "r2", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "go", side: "right" },
      { id: "r4", ...POS.right, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "out", side: "right" },
    ],
  },
  {
    id: "fade-flat",
    name: "Fade-Flat (Goal Line)",
    defense: "man",
    qb: QB,
    formation: "Doubles Tight",
    purpose: "Quick fade or flat for a goal-line score.",
    keyRead: "Throw fade vs. tight man, flat vs. soft.",
    tags: ["short", "goalline", "redzone"],
    receivers: [
      { id: "r1", x: 22, y: 4, route: "go", side: "left" },
      { id: "r2", x: 36, y: 4, route: "flat", side: "left" },
      { id: "r3", ...POS.center, route: "hitch", side: "right", isCenter: true },
      { id: "r4", x: 64, y: 4, route: "flat", side: "right" },
      { id: "r5", x: 78, y: 4, route: "go", side: "right" },
    ],
  },

  // ===== ZONE BEATERS (3x3) =====
  // Kid-named plays built to attack the 3-3 zone (3 short, 3 deep).
  // keyRead = what the QB says out loud. notes = the huddle cue for the kids.
  {
    id: "zb-pizza",
    name: "Pizza",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose:
      "Horizontal stretch: four quick targets sideline-to-sideline overload the three short zone defenders.",
    keyRead: "Pick a side before the snap. Throw the flat FAST — if he's covered, the hitch is right behind him.",
    notes: "Deliver the pizza to the sideline! Catch it, turn, and run up the open grass.",
    tags: ["short", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "hitch", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "flat", side: "left" },
      { id: "r3", ...POS.center, route: "sit", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "flat", side: "right" },
      { id: "r5", ...POS.farRight, route: "hitch", side: "right" },
    ],
  },
  {
    id: "zb-oreo",
    name: "Oreo",
    defense: "zone",
    qb: QB,
    formation: "Spread",
    purpose:
      "Slot go routes pull the three deep defenders back; the outside hitches (cookies) and center sit (cream) settle in the empty short grass.",
    keyRead: "Throw the hitch AWAY from the middle defender. If both are covered, the cream (center) is always open.",
    notes: "Cookies on the outside, cream in the middle. Hitch catchers: stop, turn, face the QB — don't drift.",
    tags: ["short", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "hitch", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "go", side: "left" },
      { id: "r3", ...POS.center, route: "sit", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "hitch", side: "right" },
    ],
  },
  {
    id: "zb-popcorn",
    name: "Popcorn",
    defense: "zone",
    qb: QB,
    formation: "Trips Left",
    purpose:
      "Instant bubble screen with two blockers. Zone flat defenders play deep off the line, so the edge grass is free.",
    keyRead: "Snap it, throw the popcorn to the wide side right away. Don't hold it.",
    notes: "Blockers: build a wall and freeze. Runner: catch FIRST, then follow the wall up the sideline.",
    tags: ["short", "screen", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "screen", side: "left" },
      { id: "r2", ...POS.left, route: "block", side: "left" },
      { id: "r3", ...POS.slotLeft, route: "block", side: "left" },
      { id: "r4", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "zb-waves",
    name: "Waves",
    defense: "zone",
    qb: QB,
    formation: "Trips Right",
    purpose:
      "Flood: three routes at three depths on one side. Two zone defenders cannot cover three waves.",
    keyRead: "Look deep first, then come down: big wave (go), middle wave (out), little wave (flat). Throw the open one.",
    tags: ["short", "third-long", "zone-beater"],
    notes: "Three waves crash the same beach — deep, middle, short. Somebody is ALWAYS open.",
    receivers: [
      { id: "r1", ...POS.farLeft, route: "post", side: "left" },
      { id: "r2", ...POS.center, route: "sit", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "flat", side: "right" },
      { id: "r4", ...POS.right, route: "out", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "zb-ladder",
    name: "Ladder",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose:
      "Levels: three crossing routes at climbing depths slice the seams between short and deep zones.",
    keyRead: "Climb the ladder: low rung (drag) first, then middle rung (in), then top rung (dig). Throw the lowest OPEN rung.",
    notes: "Never skip to the top of the ladder — take the easy rung and run.",
    tags: ["short", "third-long", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "drag", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "in", side: "left" },
      { id: "r3", ...POS.center, route: "sit", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "dig", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "zb-rocket",
    name: "Rocket",
    defense: "zone",
    qb: QB,
    formation: "Spread",
    purpose:
      "Seam shots: two slot verticals split the three deep defenders while outs hold the flat defenders wide.",
    keyRead: "Watch the deep MIDDLE defender. Throw the rocket on the side he can't reach.",
    notes: "Rocket runners: run straight as an arrow, look for the ball over your inside shoulder at 10 yards.",
    tags: ["deep", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "out", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "go", side: "left" },
      { id: "r3", ...POS.center, route: "sit", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "out", side: "right" },
    ],
  },
  {
    id: "zb-rainbow",
    name: "Rainbow",
    defense: "zone",
    qb: QB,
    formation: "Doubles",
    purpose:
      "Smash: hitch under, corner over — a high-low sandwich on the short sideline defender.",
    keyRead:
      "Pick a side and watch the short sideline defender: if he sits on the hitch, throw the rainbow over his head. If he backs up, take the easy hitch.",
    notes: "One short, one long — he can't guard both. Corner runners: break to the front cone of the end zone.",
    tags: ["deep", "redzone", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "hitch", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "corner", side: "left" },
      { id: "r3", ...POS.center, route: "sneak", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r5", ...POS.farRight, route: "hitch", side: "right" },
    ],
  },
  {
    id: "zb-safety-net",
    name: "Safety Net",
    defense: "zone",
    qb: QB,
    formation: "Spread",
    purpose:
      "Must-convert: verticals clear the deep three, the dig works the open middle, and the center sit is the guaranteed outlet.",
    keyRead: "Count 'one-two': gos clear it out, throw the dig behind the short defenders. In trouble? Hit the net (center).",
    notes: "We NEVER take a sack — the net is always under you.",
    tags: ["third-long", "deep", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.slotLeft, route: "dig", side: "left" },
      { id: "r3", ...POS.center, route: "sit", side: "right", isCenter: true },
      { id: "r4", ...POS.slotRight, route: "corner", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "zb-thunder",
    name: "Thunder",
    defense: "zone",
    qb: QB,
    formation: "Doubles Tight",
    purpose:
      "Goal line: quick flats to both edges plus a center sneak — the ball is out before the zone can squeeze.",
    keyRead: "Quick count! Throw your best-side flat before the defense moves. Center sneak is plan B.",
    notes: "Catch it and DIVE for the line — no dancing at the goal line.",
    tags: ["goalline", "redzone", "short", "zone-beater"],
    receivers: [
      { id: "r1", x: 22, y: 4, route: "flat", side: "left" },
      { id: "r2", x: 36, y: 4, route: "slant", side: "left" },
      { id: "r3", ...POS.center, route: "sneak", side: "right", isCenter: true },
      { id: "r4", x: 64, y: 4, route: "slant", side: "right" },
      { id: "r5", x: 78, y: 4, route: "flat", side: "right" },
    ],
  },
  {
    id: "zb-turtle",
    name: "Sneaky Turtle",
    defense: "zone",
    qb: QB,
    formation: "Trips Right",
    purpose:
      "Trick: pump the screen right to pull the whole zone, then flip to the center leaking left into empty grass.",
    keyRead: "Pump the screen right — sell it! Then flip to the turtle sneaking out the back door left.",
    notes: "Center: count 'one banana, two banana' — THEN sneak left. Don't leave early!",
    tags: ["trick", "short", "redzone", "zone-beater"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.center, route: "leak", side: "left", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "screen", side: "right" },
      { id: "r4", ...POS.right, route: "block", side: "right" },
      { id: "r5", ...POS.farRight, route: "block", side: "right" },
    ],
  },

  // ===== RUN PLAYS =====
  {
    id: "qb-sweep-right",
    name: "QB Sweep Right",
    defense: "zone",
    qb: QB,
    qbAction: "keep-right",
    formation: "Doubles",
    playType: "run",
    purpose: "QB takes the snap and sweeps wide right behind blockers.",
    keyRead: "Follow your blocker; cut up when the edge sets.",
    tags: ["run", "short"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.left, route: "block", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "block", side: "right" },
      { id: "r5", ...POS.farRight, route: "block", side: "right" },
    ],
  },
  {
    id: "rb-dive",
    name: "RB Dive",
    defense: "man",
    qb: QB,
    formation: "I-Form",
    playType: "run",
    purpose: "Quick handoff up the gut; built for short yardage.",
    keyRead: "Hit the A-gap behind the center; bounce only if jammed.",
    tags: ["run", "short", "goalline"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.left, route: "block", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "block", side: "right" },
      { id: "r5", ...POS.backfield, route: "dive", side: "right", isRunner: true },
    ],
  },
  {
    id: "jet-sweep-left",
    name: "Jet Sweep Left",
    defense: "zone",
    qb: QB,
    formation: "Trips Right",
    playType: "run",
    purpose: "Pre-snap motion to the QB for a fast handoff and edge run.",
    keyRead: "Hit the edge at full speed; cut behind your block.",
    tags: ["run", "trick"],
    motion: { receiverId: "r4", toX: 50, toY: 8 },
    receivers: [
      { id: "r1", ...POS.farLeft, route: "block", side: "left" },
      { id: "r2", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r3", ...POS.slotRight, route: "block", side: "right" },
      { id: "r4", ...POS.farRight, route: "sweep", side: "left", isRunner: true },
      { id: "r5", ...POS.backfield, route: "block", side: "right" },
    ],
  },
  {
    id: "counter-trey",
    name: "Counter Right",
    defense: "man",
    qb: QB,
    formation: "Strong Right",
    playType: "run",
    purpose: "Misdirection: fake left, run right behind a puller.",
    keyRead: "Wait one count, follow the puller, hit the C-gap.",
    tags: ["run", "trick"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "block", side: "left" },
      { id: "r2", ...POS.left, route: "block", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "block", side: "right" },
      { id: "r5", ...POS.backfield, route: "counter", side: "right", isRunner: true },
    ],
  },
  {
    id: "qb-keep-draw",
    name: "QB Draw",
    defense: "zone",
    qb: QB,
    qbAction: "scramble",
    formation: "Empty",
    playType: "run",
    purpose: "Show pass, then QB tucks and runs through soft middle.",
    keyRead: "Drop two steps; if the middle opens, go.",
    tags: ["run", "third-long", "trick"],
    receivers: [
      { id: "r1", ...POS.farLeft, route: "go", side: "left" },
      { id: "r2", ...POS.left, route: "go", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.right, route: "go", side: "right" },
      { id: "r5", ...POS.farRight, route: "go", side: "right" },
    ],
  },
  {
    id: "reverse-flea",
    name: "Reverse",
    defense: "man",
    qb: QB,
    formation: "Trips Left",
    playType: "run",
    purpose: "Hand to one back, who pitches across to a crossing back.",
    keyRead: "Sell the first run, then run away from pursuit.",
    tags: ["run", "trick"],
    motion: { receiverId: "r5", toX: 30, toY: 10 },
    receivers: [
      { id: "r1", ...POS.farLeft, route: "block", side: "left" },
      { id: "r2", ...POS.left, route: "block", side: "left" },
      { id: "r3", ...POS.center, route: "delay", side: "right", isCenter: true },
      { id: "r4", ...POS.farRight, route: "block", side: "right" },
      { id: "r5", ...POS.backfieldRight, route: "sweep", side: "left", isRunner: true },
    ],
  },
];

// 6 defenders for both man (3-2-1 / mirror) and zone (3-3 zone) — 6v6 reality.
export function defensePositions(d: "zone" | "man") {
  if (d === "zone") {
    // 3-3 zone: 3 underneath flat/curl, 3 deep
    return [
      { x: 18, y: 50, label: "Z" }, // left flat
      { x: 50, y: 52, label: "Z" }, // middle hook
      { x: 82, y: 50, label: "Z" }, // right flat
      { x: 22, y: 30, label: "Z" }, // deep left
      { x: 50, y: 26, label: "Z" }, // deep middle
      { x: 78, y: 30, label: "Z" }, // deep right
    ];
  }
  // Man: 5 defenders mirroring receivers + 1 deep safety
  return [
    { x: 14, y: 56, label: "M" },
    { x: 30, y: 56, label: "M" },
    { x: 50, y: 56, label: "M" },
    { x: 70, y: 56, label: "M" },
    { x: 86, y: 56, label: "M" },
    { x: 50, y: 30, label: "S" }, // deep safety
  ];
}
