/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WristbandRouteImport } from './routes/wristband'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlaysheetRouteImport } from './routes/playsheet'
import { Route as HalftimeRouteImport } from './routes/halftime'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as DefenseRouteImport } from './routes/defense'
import { Route as IndexRouteImport } from './routes/index'

const WristbandRoute = WristbandRouteImport.update({
  id: '/wristband',
  path: '/wristband',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysheetRoute = PlaysheetRouteImport.update({
  id: '/playsheet',
  path: '/playsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const HalftimeRoute = HalftimeRouteImport.update({
  id: '/halftime',
  path: '/halftime',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const DefenseRoute = DefenseRouteImport.update({
  id: '/defense',
  path: '/defense',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/defense': typeof DefenseRoute
  '/designer': typeof DesignerRoute
  '/halftime': typeof HalftimeRoute
  '/playsheet': typeof PlaysheetRoute
  '/practice': typeof PracticeRoute
  '/stats': typeof StatsRoute
  '/wristband': typeof WristbandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/defense': typeof DefenseRoute
  '/designer': typeof DesignerRoute
  '/halftime': typeof HalftimeRoute
  '/playsheet': typeof PlaysheetRoute
  '/practice': typeof PracticeRoute
  '/stats': typeof StatsRoute
  '/wristband': typeof WristbandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/defense': typeof DefenseRoute
  '/designer': typeof DesignerRoute
  '/halftime': typeof HalftimeRoute
  '/playsheet': typeof PlaysheetRoute
  '/practice': typeof PracticeRoute
  '/stats': typeof StatsRoute
  '/wristband': typeof WristbandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/defense'
    | '/designer'
    | '/halftime'
    | '/playsheet'
    | '/practice'
    | '/stats'
    | '/wristband'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/defense'
    | '/designer'
    | '/halftime'
    | '/playsheet'
    | '/practice'
    | '/stats'
    | '/wristband'
  id:
    | '__root__'
    | '/'
    | '/defense'
    | '/designer'
    | '/halftime'
    | '/playsheet'
    | '/practice'
    | '/stats'
    | '/wristband'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefenseRoute: typeof DefenseRoute
  DesignerRoute: typeof DesignerRoute
  HalftimeRoute: typeof HalftimeRoute
  PlaysheetRoute: typeof PlaysheetRoute
  PracticeRoute: typeof PracticeRoute
  StatsRoute: typeof StatsRoute
  WristbandRoute: typeof WristbandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wristband': {
      id: '/wristband'
      path: '/wristband'
      fullPath: '/wristband'
      preLoaderRoute: typeof WristbandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playsheet': {
      id: '/playsheet'
      path: '/playsheet'
      fullPath: '/playsheet'
      preLoaderRoute: typeof PlaysheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halftime': {
      id: '/halftime'
      path: '/halftime'
      fullPath: '/halftime'
      preLoaderRoute: typeof HalftimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defense': {
      id: '/defense'
      path: '/defense'
      fullPath: '/defense'
      preLoaderRoute: typeof DefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefenseRoute: DefenseRoute,
  DesignerRoute: DesignerRoute,
  HalftimeRoute: HalftimeRoute,
  PlaysheetRoute: PlaysheetRoute,
  PracticeRoute: PracticeRoute,
  StatsRoute: StatsRoute,
  WristbandRoute: WristbandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
