/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidelineRouteImport } from './routes/sideline'
import { Route as IndexRouteImport } from './routes/index'

const SidelineRoute = SidelineRouteImport.update({
  id: '/sideline',
  path: '/sideline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sideline': typeof SidelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sideline': typeof SidelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sideline': typeof SidelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sideline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sideline'
  id: '__root__' | '/' | '/sideline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidelineRoute: typeof SidelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sideline': {
      id: '/sideline'
      path: '/sideline'
      fullPath: '/sideline'
      preLoaderRoute: typeof SidelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidelineRoute: SidelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
